language: ruby
# only run CI-builds on master branch
branches:
  only:
    - main
rvm:
  - 2.4.0
# set execution permission on our build script
before_script:
  - chmod +x ./scripts/cibuild
# path to our build script.
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false