# Standard
title: Electric Jones
email: hey@electricjones.me
description: >- # this means to ignore newlines until "baseurl:"
  I thrive on creative collaboration with smart, passionate people solving complex problems using computer science. 
  I also view life like an old school action rpg, and this site is the map I leave for others to join me on my journey.
url: "https://electricjones.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  electricjones

# Variables
social:
  github: https://github.com/electricjones
  linkedin: https://linkedin.com
  instagram: https://instagram.com

# Configuration
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: rust
    css_class   : 'code-block_wrap chroma-body chroma'

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
