# Standard
title: Electric Jones
email: hey@electricjones.me
description: >- # this means to ignore newlines until "baseurl:"
  I thrive on creative collaboration with smart, passionate people solving complex problems using computer science. 
  I also view life like an old school action rpg, and this site is the map I leave for others to join me on my journey.
url: "https://electricjones.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  electricjones

# Variables
social:
  github: https://github.com/electricjones
  linkedin: https://linkedin.com
  instagram: https://instagram.com

# Configuration
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: rust
    css_class   : 'code-block_wrap chroma-body chroma'

# Pagination and Indexes
pagination:
  enabled: true
  debug: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'post-index.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts for :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: true       # Whether to replace all uppercase letters with their lowercase counterparts

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'post-index.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

gems:
  - jekyll-paginate-v2
